agent:
  policy_type: mlp # or "mlp"
  features: 256
  nheads: 8
  num_layers: 3
  pi_arch: [256, 256]
  qf_arch: [128, 128]
  tau: 0.005
  ent_coef: 0.2
training:
  algorithm: sac # or "ppo"
  learning_rate: 0.0003
  gamma: 0.99
  device: cpu
